backend:
  name: github
  repo: cristian-encalada/dev  # Replace with your GitHub username and repository name
  branch: main  # Replace with the branch name where your website is hosted

media_folder: "assets/img"
public_folder: "/img"

collections:
  - name: "blog"  # Replace with the desired name for your collection
    label: "Blog"  # Replace with the desired label for your collection
    folder: "_posts"  # Replace with the folder name where your blog posts will be stored
    create: true
    fields:
      - { name: "title", label: "Title" }  # Add more fields as needed for your blog posts
      - { name: "date", label: "Date", widget: "datetime" }  # Example of a date field
      - { name: "author", label: "Author" }
      - { name: "body", label: "Body", widget: "markdown" }  # Example of a Markdown field
      # Add more fields as needed for your blog posts

# Add more collections as needed for your content types
# Refer to the Netlify CMS documentation for additional configuration options
